version: '3'
services:
    backend1-web:
        build: ./etc/nginx
        container_name: backend1-web
        volumes:
            - "./etc/nginx/backend1.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
            - "${SOURCE_PATH_BACKEND1}:/var/www/html"
        restart: always
        env_file:
            - ".env"
        ports:
            - "3001:80"
            - "3002:443"
        networks:
            service1_net:
                ipv4_address: 172.22.128.11
    backend2-web:
        build: ./etc/nginx
        container_name: backend2-web
        volumes:
            - "./etc/nginx/backend2.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
            - "${SOURCE_PATH_BACKEND2}:/var/www/html"
        restart: always
        env_file:
            - ".env"
        ports:
            - "4001:80"
            - "4002:443"
        networks:
            service1_net:
                ipv4_address: 172.22.128.12
    backend-master-web:
        build: ./etc/nginx
        container_name: backend-master
        volumes:
            - "./etc/nginx/backendmaster.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
        restart: always
        env_file:
            - ".env"
        ports:
            - "5001:80"
            - "5002:443"
        networks:
            service1_net:
                ipv4_address: 172.22.128.10
networks:
    service1_net:
        ipam:
            driver: default
            config:
                - subnet: 172.22.0.0/16